<?php
$_product = $block->getProduct();
?>

<?php if($_product->getPsnIsPersonalisable()):?>
    <div class="personalisation-preview front front-text text" data-personalisation-area="front">
        <span></span>
    </div>
    <div class="personalisation-preview front icon" data-personalisation-area="front"></div>
    <div class="personalisation-preview front pattern" data-personalisation-area="front"></div>
    <div class="personalisation-preview back back-text text hide" data-personalisation-area="back">
        <span></span>
    </div>
<?php endif ?>